### ISSUE TITLE
Delimit with "end of word" the regexes for the keywords "pi" and "sigma".

### ISSUE THREAD

**Issue by maggesi** [LPCIC/elpi-lang#1]
How to detect the problem:
type in an Elpi file a word containing internally the substring `pi` (or `sigma`), such as
`typing` and see the colouration of the "pi".

Notice that this problem often breaks the syntax detection of the rest of the file.

**Comment by gares** [comment]
It should be fixed. I'll push the new version to the app store soon, in the meanwhile you can usa a symlink to a checkout of this repo as in:
```
gares@ollypat:~/LPCIC/coq-elpi-lang$ ls -l ~/.vscode-oss/extensions/
...
lrwxrwxrwx  1 gares gares   28 sept.  6 17:12 elpi-lang -> /home/gares/LPCIC/elpi-lang/
...
```
