### ISSUE TITLE
bug: trace browser not showing a failed attempt

### ISSUE THREAD

**Issue by gares** [LPCIC/elpi-lang#14]
[trace.tmp.json.zip](https://github.com/LPCIC/elpi-lang/files/11027052/trace.tmp.json.zip)

**Comment by jwintz** [comment]
The elaborator outputs: `input trace is broken since step_id 7`. Am I missing something ?

**Comment by gares** [comment]
Hi @jwintz , I opened the bug just to not lose the trace, didn't want you to look into it, sorry.
I believe the bug is in the trace elaborator (so it is for me).

On the other hand I think I fixed the bug you see in the very last release of elpi, but I'll need to double check.

**Comment by jwintz** [comment]
Ok ! No worries. Thanks.

**Comment by gares** [comment]
Another example where the rule of an attempt is the wrong one (but the siblings are the right ones):
[traced.tmp.json.gz](https://github.com/LPCIC/elpi-lang/files/11232598/traced.tmp.json.gz)

**Comment by gares** [comment]
Apparently a failed attempt is only shown if it is followed by a successful attempt.
