### ISSUE TITLE
Slow browsing

### ISSUE THREAD

**Issue by gares** [LPCIC/elpi-lang#4]
Loading this trace (vscode 1.72) takes forever. In particular a few seconds before the UI shows the card, then a few second before each card shows up its goal text. The third card text is "Cut", and it still takes time for it to appear.

If I had to point the finger, it would be syntax highlighting code. Is there an easy way to disable it, so that I can validate or refuse this thesis?

[trace-qui-rame.js.gz](https://github.com/LPCIC/elpi-lang/files/9851403/trace-qui-rame.js.gz)

CC @jwintz

**Comment by jwintz** [comment]
Oh my. Sorry, I missed the notification. Your thesis actually fully makes sense, should vscode send the highlighting requests one by one. I'll create an option to deactivate syntax highlighting ASAP.

This issue should be addressed together with the handling of very large traces, that is, when required memory at hand exceeds what vscode allows for an extension, should heuristics be involved to activate/deactivate such features.

**Comment by gares** [comment]
Thanks!

**Comment by jwintz** [comment]
https://github.com/LPCIC/elpi-lang/pull/5 has just bee submitted. It makes syntax highlighting optional.

![Screenshot from 2022-11-19 13-28-21](https://user-images.githubusercontent.com/3277054/202852216-efc627bf-70d0-4e69-baf9-b0fbe91d5d84.png)

![Screenshot from 2022-11-19 13-29-54](https://user-images.githubusercontent.com/3277054/202852227-320d007d-d39b-4fcb-96b7-9e112b6b3f9c.png)
